# To calculate E_CAT aggregate
a=int(input("Enter your E_CAT obtained marks:"))
b=int(input("Enter your Matric obtained marks:"))
c=int(input("Enter your intermediate part 1 obtained marks:"))
d=int(input("Enter your total E_CAT marks:"))
e=int(input("Enter your Matric total marks:"))
f=int(input("Enter your intermediate part 1 marks:"))
a=float(a*100/d)
b=float(b*100/e)
c=float(c*100/f)
a=float(a*33/100)
b=float(b*17/100)
c=float(c*50/100)
print("your aggregate is:",a+b+c)